### ISSUE TITLE
Bug: Inventory Not Resetting Correctly

### ISSUE THREAD

**Issue by ShiveringRusty** [SkyWars/SkyWars#81]
Our server version is 1.7.2. Our SkyWars version is 1.4.2.

We use Multiverse and Multiverse Inventories.  SkyWars's inventory reset feature works fine when a player joins the game while in the survival world, but it lets them keep their creative inventory in the survivial world after the game if they join while in the creative world.  Is there a fix for this?  I can change the permissions so they can't join the game while in the creative world, but it would be great if there's a better solution.  Thanks!  

There were no server.log errors.

Here's the link to the /sw report: https://gist.github.com/anonymous/aa2367babb8779538864

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars.

However, in any case, I believe this issue should be fixed as of https://github.com/SkyWars/SkyWars/commit/1e7669f2f691b768815a8911d2f0c98ac97de5bd. If you still are using SkyWars and still have this issue after the next update, reply and I will re-open.

**Comment by WouterK12** [comment]
Hi,

My server is running CraftBukkit 1.12.2 with SkyWars 2.2.0.
Instead of Multiverse-Inventories, I am using PerWorldInventory (latest version)
/sw report: https://gist.github.com/anonymous/5266bd3d0457fc9024fcee1a7a803d7b
As ShiveringRusty mentioned a couple years ago, he had a problem with the inventory clearing system.
I am still having this error. (The winner has still it's inventory in a new game.)
I don't have any server.log errors.
How do I fix this?

Thanks in advance,
Wouter
